# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    commands:
      - echo "installing Pip packages"

  pre_build:
    commands:
      - echo "Creating Docker Image"


  build:
    commands:
      - docker build -t flask_image .
      - echo Image built successfully

  post_build:
    commands:
      - docker images
      - echo Run the Image
      - docker run  -d -p 5000:5000 flask_image:latest
      - echo Test The Docker Services
      - curl -kiv http://127.0.0.1:5000/incomes


