# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    commands:
      - echo "installing Pip packages"

  pre_build:
    commands:
      - echo "Creating Docker Image"


  build:
    commands:
      - docker build -t flask_image .
      - echo Image built successfully

  post_build:
    commands:
      - docker images
      - docker tag flask_image:latest 767397898761.dkr.ecr.us-west-2.amazonaws.com/demoflaskapp:latest
      - docker push 767397898761.dkr.ecr.us-west-2.amazonaws.com/demoflaskapp:latest
      - echo Run the Image
      - docker run  -d -p 5000:5000 flask_image:latest
      - echo Check the Running Containers
      - docker ps
      - echo Test The Docker Services



